### PR TITLE
Team Anchor social login 

### PR DESCRIPTION
**Pull request by ChibuzoEkwue**
# Description
Worked on the google oauth landing page

**Closes #issue_number_here**

# Changes proposed

## What did you do?

Added the google login feature

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

### CODE REVIEW

**Review by ikennarichard — DISMISSED** [review]
@PrudentBird  is this ok now?

**Review by ikennarichard — COMMENTED** [review]
Fix linter errors

**Review by ikennarichard — APPROVED** [review]
Completed

**Review by prudentbird — CHANGES_REQUESTED** [review]
this code would break production, you are attempting to use a client side ENV, and in pipeline we have only server side ENV

**Pull request closed without merging**
