### PR TITLE
feat: create upgrade plan page (payments) - Team Bulldozer

### PR DESCRIPTION
**Pull request by Praizee**
# Description

# Changes proposed

## What were you told to do?

SETTINGS PAGE -> Implement Upgrade Payment Plan Page

## What did you do?

I implemented the upgrade payment plan page, according to the design, along with the success and failed upgrade modals

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

image

image

image

image

### CODE REVIEW

**Comment by buka4rill** [comment]
Please correct the PR name

**Comment by Praizee** [comment]
> Please correct the PR name

Done

**Comment by buka4rill** [comment]
What issue does this PR solve? Link it

**Comment by Praizee** [comment]
> What issue does this PR solve? Link it

It's not an issue.
I and other FE devs are working on pricing/payment
Seems this page (and others) were newly added to the design

**Comment by buka4rill** [comment]
That means you are implementing a backend issue. Ask the backend to provide that issue

**Review by kleenpulse — APPROVED** [review]

**Review by Samadeen — APPROVED** [review]

**Comment by Praizee** [comment]
@Samadeen 
Should I update now, or wait?

image

**Review by phoenixdahdev — APPROVED** [review]

**Pull request merged**
