### PR TITLE
feat: members page and invite to org - Team Anchor 

### PR DESCRIPTION
**Pull request by Froches**
# Description

**Closes #852**

# Changes proposed
Roles & Permissions Page and Invite to Org
## What were you told to do?
Implement Roles & Permissions Page and Invite to Org

Roles & Permissions Page and Invite to Org
## What did you do?
Implemented the Invite to Org Modal functionality on the Members Page.

Updated the Invite to org modal with API integrations.
# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos
Screenshot 2024-07-31 at 3 36 13 AM
Screenshot 2024-08-01 at 2 05 17 AM

### CODE REVIEW

**Comment by Froches** [comment]
@ikennarichard

**Comment by billmal071** [comment]
PR title should be feat: create the members page and invite to org - Team Anchor

**Review by billmal071 — APPROVED** [review]
LGTM

**Review by ikennarichard — APPROVED** [review]
Completed

**Pull request merged**
