### PR TITLE
Feat/165 email templat layout header and footer

### LINKED ISSUE #165: [Feature]: EMAIL TEMPLATES -> Email template layout (Header and Footer)
### Description

_Create an Email template layout (Header and Footer) according to the design_

### Acceptance Criteria

- The email template layout must be responsive
- The email template layout must be done according to the design
- The email template layout must be divided into header and footer

### Requirements	

The following items should be available for the layout

1. Header
2. Footer

### Tests

- [ ] Ensure template layout is responsive
- [ ] Ensure template layout can receive dynamic data according to what will be displayed
- [ ] Ensure template layout is displayed properly according to design and requirements

###  Tasks

- [ ] Create an email template header
- [ ] Create an email template footer
- [ ] Template header and footer must be responsive on Bigger screens, tablet screens and mobile screens
- [ ] Create a unit test to ensure template layout works as expected

### Links

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=67-30514&m=dev).

# IMAGES
Header
Footer

### PR DESCRIPTION
**Pull request by RoyalTechqueen**
# Description

**Closes #165 **

# Changes proposed

## What were you told to do?

[Feature]: EMAIL TEMPLATES -> Email template layout (Header and Footer) #165

## What did you do?
I created an email template folder under the admin folder then created header and footer subfolders. I also uploaded a tiktok Svg into the public folder. I created the header which includes a logo and a text. Then the footer that includes social icons and texts.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

Screenshot (52)
Screenshot (53)
Screenshot (54)
Screenshot (55)

# Screenshots/Videos

### CODE REVIEW

**Comment by oreoluwa212** [comment]
Where were you told in your issue to do that header?

**Review by oreoluwa212 — CHANGES_REQUESTED** [review]
Let me know why you have done the header and also attach your tests screenshots and a video to your component working after you pulled from dev

**Comment by oreoluwa212** [comment]
Did you implement the design? Your screenshot is different from what I see in your issue screenshot

**Comment by RoyalTechqueen** [comment]
> Where were you told in your issue to do that header?

Screenshot (57)

**Comment by RoyalTechqueen** [comment]
> Let me know why you have done the header and also attach your tests screenshots and a video to your component working after you pulled from dev

it was stated in the issue to create both header and footer for email template layout
and these are my test screenshots
Screenshot (54)
Screenshot (55)

**Comment by RoyalTechqueen** [comment]
> Did you implement the design? Your screenshot is different from what I see in your issue screenshot

Yes I implemented the design, the screenshots shows that because i used the exact background color that i hardcoded using style with  this color format '#fffffff'. But i had to change it to the closest color from global.css when the test failed

**Review by oreoluwa212 — CHANGES_REQUESTED** [review]
You need to pull from dev, your PR is outdated. And also dont edit my page.tsx in home, put your header and footer components inside guide's page.tsx at the bottom for people who meed your component to see

**Comment by RoyalTechqueen** [comment]
> You need to pull from dev, your PR is outdated. And also dont edit my page.tsx in home, put your header and footer components inside guide's page.tsx at the bottom for people who meed your component to see

I have done that

**Review by oreoluwa212 — APPROVED** [review]

**Pull request merged**
