### PR TITLE
Members Page and Invite To Org - Team Anchor

### PR DESCRIPTION
**Pull request by Froches**
# Description

**Closes #852**

# Changes proposed

## What were you told to do?
Create the Invite to Org feature and implement Roles and permissions page. 

Roles & Permissions and Invite to Org 
## What did you do?
Implemented the UI for Members Page and the Invite to Org Modal as well as functionality for the Copy link to clipboard feature and integration of the API

Updated the invite to org modal with API integration. 
# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

Screenshot 2024-08-01 at 9 24 08 AM

Screenshot 2024-07-31 at 3 36 13 AM

### CODE REVIEW

**Review by ikennarichard — APPROVED** [review]
Completed

**Comment by ikennarichard** [comment]
@billmal071 @PrudentBird @raji-ayyub please review

**Comment by billmal071** [comment]
1. Bad branch name: feat/create-members-page
2. Add the issue number
3. Fill out the rest of the PR template, add screenshots
4. Bad commit messages

**Comment by billmal071** [comment]
PR title is also wrong.

**Review by billmal071 — APPROVED** [review]
Files look good.

**Review by prudentbird — CHANGES_REQUESTED** [review]
Fix the PR title, and branch name

**Review by Maiqel1 — COMMENTED** [review]
pr title, pr description, branch name dont follow proper guidelines

**Review by frank1003A — APPROVED** [review]

**Pull request closed without merging**
