### PR TITLE
Feat/158 email welcome with image

### LINKED ISSUE #158: [FEAT] EMAIL TEMPLATES > Implement welcome page WITH image
## Description
Using React email package Develop a clean and informative Welcome Email Template. This email is designed to greet new users, confirm their sign-up, and highlight key benefits of the Boilerplate service.

## Acceptance Criteria

- The email template is implemented according to the provided design, WITH an image.
- The template is responsive and displays correctly across various email clients.

### Requirements	
The email template should include the following elements:

- Main heading: "Welcome to Boilerplate!"
- Subheading: "Thanks for signing up"
- Personalized greeting (e.g., "Hi John Doe,")
- Welcome message and brief product description
- Section highlighting key benefits
- Call-to-action button
- Sign-off and company name

### Tests

- Ensure all elements render correctly and match the design.
- Verify responsiveness across various email clients and device sizes.
- Check that personalization fields populate correctly.
- Test the functionality of the CTA button.

###  Tasks

- [ ] Use a React email package to develop the Welcome Email Template based on the provided design and requirements.
- [ ] Implement a responsive layout that works well across different email clients.
- [ ] Set up personalization fields for the recipient's name.
- [ ] Implement the CTA button with proper styling and linking.
- [ ] Ensure all text content is editable for easy customization.
- [ ] Implement tracking parameters for the CTA button (if applicable).

# LINKS

[`FIGMA LINK`](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=7-8277&m=dev).

# IMAGES
image

### PR DESCRIPTION
**Pull request by ruxy1212**
# Description
Built the email template for Welcome page with image.

Closes #158

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?

[FEAT] EMAIL TEMPLATES > Implement welcome page WITH image
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=402-45684&m=dev

## What did you do?

I developed a clean and informative Welcome Email Template using React email package, designed to greet new users, confirm their sign-up, and highlight key benefits of the Boilerplate service.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

fnl2

page-m

page-w

### CODE REVIEW

**Comment by oreoluwa212** [comment]
Did you understand the folder structure at all?? Why am I seeing email inside my src??

**Comment by oreoluwa212** [comment]
Export images as svg or else,no way

**Comment by oreoluwa212** [comment]
If you dont put all your stuff in just one folder inside components/common or component/layout as the case maybe, oyo

**Comment by oreoluwa212** [comment]
Also, proper naming of files

**Comment by ruxy1212** [comment]
> Did you understand the folder structure at all?? Why am I seeing email inside my src??

Email has been inside src since na, I did not create the structure. Were you not the one that merged the person who created the template without image, was it not inside the /src directory?



> Export images as svg or else,no way

If you've ever worked with email templates, you should know that email images don't work with relative linking but absolute, and svg in particular when linked as img tags will not display in some email servers like GMAIL. The fix is to use it as a component. It will show 404 any other way. Check my screenshot, that is the React-Email server output.



> If you dont put all your stuff in just one folder inside components/common or component/layout as the case maybe, oyo

For the layout, I had create the component myself because CodedLibra told me the ticket for email layout is too small so I did it so others can use. Since the ticket did not state that each template should build its own header and footer

> Also, proper naming of files

The file name is what React-Email suggest, as you can see, the other email template there `no-image.tsx` was created by who set up the Email stuff, so that is the standard for REACT EMAIL.

image

**Review by prudentbird — CHANGES_REQUESTED** [review]
Go and use icons from lucide react and delete all those icons you created

**Comment by ruxy1212** [comment]
> Go and use icons from lucide react and delete all those icons you created

image

Lucide react doesn't have a lot of social icons, the only one similar there with what I need is instagram, any other suggestions?

**Pull request closed without merging**
