### PR TITLE
feat: create settings page for superadmin user (team KIMIKO)

### PR DESCRIPTION
**Pull request by abanicaisse**
# Description
Create a settings page for the superadmin dashboard

**Closes #issue_number_here**

# Changes proposed
- Create a new settings page on the superadmin
- Implement user profile upload functionality

## What were you told to do?
- Create the superadmin settings page
- Ensure the page is responsive and work on all devices
- Ensure the page works as intended

## What did you do?
- Create a new route in the superadmin dashboard at dashboard/admin/settings
- Create the UI of the page according to the design provided
- Ensure the page was responsive across multiple device screen sizes
- Create the profile pic upload functionality
- Ensure the page work as intended

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos
Screenshot 2024-07-29 at 20 37 02

Screenshot 2024-07-29 at 20 37 47

### CODE REVIEW

**Review by Justfemi — APPROVED** [review]

**Comment by buka4rill** [comment]
please rename this PR from `Feat` to `feat`

**Comment by abanicaisse** [comment]
> please rename this PR from `Feat` to `feat`

@buka4rill Done

**Comment by buka4rill** [comment]
link the PR issue

**Comment by abanicaisse** [comment]
> link the PR issue

It's not linked to an issue on the repo.

This page is a newly added page on the design. I and other FE from other teams are working on the superadmin pages, this is just one of the tasks/features we were asked by our team leads to work on.

**Review by prudentbird — APPROVED** [review]

**Pull request merged**
