### PR TITLE
fix: add base url (Team Kimiko)

### LINKED ISSUE #882: [Fix]:  Update base url
### Description

Fix base url for jobs request

### Acceptance Criteria

Fetch Base Url from env

### Links

| [`FIGMA LINK`](LINK_HERE)

### Images

image

### PR DESCRIPTION
**Pull request by Goketech**
# Description

**Closes #882 **

# Changes proposed

Fix the base url for fetching jobs

## What did you do?

I updated the url used to fetch jobs

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

Screenshot (452)

### CODE REVIEW

**Review by prudentbird — APPROVED** [review]

**Comment by billmal071** [comment]
1. Add screenshot
2. Add the issue number

**Comment by billmal071** [comment]
Attach team name to PR title.

**Comment by Goketech** [comment]
@billmal071 
Updated

**Review by billmal071 — APPROVED** [review]
LGTM

**Pull request merged**
