### PR TITLE
Feat/hng 34 invitelink

### PR DESCRIPTION
**Pull request by Benieytah**
# Description

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?
Implement Invite Member Functionality with Generated Link

## What did you do?
I created a folder in src/components and wrote codes that renders and invite section and when the toggle switch is turned on(enabled) it renders are lik and the link can be copied and shared. 

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title and description of the PR is clear and explains the approach.
- [x ] I am making a pull request against the **dev branch** (left side).
- [x ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [x ] I am only making changes to files I was requested to.

# Screenshots/Videos!
checklint
I'm finding it difficult to upload my videos but basically it works when the toggle is switched on. and I used a dummy Api and the url is in the code.

### CODE REVIEW

**Review by oreoluwa212 — CHANGES_REQUESTED** [review]
Conflicting files, update from upstream should be fetched

Update your PR to include the necessary details including what you did, screenshots, videos, and pnpn and lint tests

Images convention: public > images > yourpagename > image1.svg 
You are to remove all changes you made to globals.css, page.tsx, tailwind.config etc

Your components need not to be added to the page.tsx

**Comment by Benieytah** [comment]
> Conflicting files, update from upstream should be fetched
> 
> Update your PR to include the necessary details including what you did, screenshots, videos, and pnpn and lint tests
> 
> Images convention: public > images > yourpagename > image1.svg You are to remove all changes you made to globals.css, page.tsx, tailwind.config etc
> 
> Your components need not to be added to the page.tsx

I've been getting errors .... my pnpm test isn't running...i have been dropping messages since. I didn't make any change in global css or tailwind.config

**Comment by Benieytah** [comment]
> Conflicting files, update from upstream should be fetched
> 
> Update your PR to include the necessary details including what you did, screenshots, videos, and pnpn and lint tests
> 
> Images convention: public > images > yourpagename > image1.svg You are to remove all changes you made to globals.css, page.tsx, tailwind.config etc
> 
> Your components need not to be added to the page.tsx

My lint test passed on my terminal but i'm etting error here

**Comment by Benieytah** [comment]
I have commited the changes

**Pull request closed without merging**
