### PR TITLE
Chore: fixed signup button 

### PR DESCRIPTION
**Pull request by phoenixdahdev**
# Changes proposed

## What did you do?
Updated password visibility state on signup

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

### CODE REVIEW

**Review by billmal071 — DISMISSED** [review]
LGTM

**Comment by billmal071** [comment]
Update PR to follow guidelines.

**Review by Maiqel1 — APPROVED** [review]

**Review by billmal071 — APPROVED** [review]
LGTM

**Comment by phoenixdahdev** [comment]
> LGTM

Done 😔😔

**Pull request merged**
