### PR TITLE
feat(HNG-68): create a reusable empty list component for career page

### LINKED ISSUE #68: [FEAT] External static page > Empty list component
# **Description**
Implement a reusable empty list components that can be rendered when there is no list available. It should accepts a graphics prop, main text prop and a sub text prop

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- A resuable component that accepts three props of image, main text and a sub text.

# **Testing**
- Write test to ensure the page renders the required contents

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed
- [ ] Write test for the implementations
- [ ] Proper commit message

# **Images**
Frame 53071

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1666-53453&m=dev)

### PR DESCRIPTION
**Pull request by Mahmud1087**
# Description

**Closes #68**

# Changes proposed

## What were you told to do?

Implement a reusable empty list components that can be rendered when there is no list available. It should accepts a graphics prop, main text prop and a sub text prop

## What did you do?

- Created 'Empty List' folder
- Developed custom EmptyList component
- Made the component to accept three props; image, mainText, and subText
- Made the component responsive on all screens
- Wrote clean and maintainable code
- Wrote test for the component and all tests passed

[Figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1666-53453&t=zxhyyAW5syGJojVt-0)

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos

Figma component image: 
Screenshot 2024-07-20 144244

My implementation: 
Screenshot (143)
Screenshot (144)
Screenshot (145)

pnpm lint pass :
Screenshot (146)

vitest pass:
Screenshot (147)

### CODE REVIEW

**Review by JulianaSau — DISMISSED** [review]
The image you posted and the one in the figma design look nothing alike. You're supposed to implement it as is

**Comment by Mahmud1087** [comment]
changes done and I've updated the pull request with the updated images

**Review by prudentbird — APPROVED** [review]

**Comment by prudentbird** [comment]
Follow the figma design so I can merge

**Comment by Mahmud1087** [comment]
I did, check the screenshots

**Review by prudentbird — DISMISSED** [review]
Use the svg from the design

**Comment by prudentbird** [comment]
> I did, check the screenshots

Check the issue you worked on, there's a different design there

**Review by prudentbird — APPROVED** [review]

**Pull request merged**
