### PR TITLE
merge pull request from #64 comment page/reply page

### PR DESCRIPTION
**Pull request by onlyeugene**
# Description

--THIS IS MY DESIGN OF THE COMMENT AND REPLY PAGE --

# Changes proposed
--None--

## What were you told to do?
-- I WAS ASKED TO DEVELOP AMD TEST THE  COMMENT AND REPLY PAGE --

<-- FEAT #64 : COMMENT PAGE AND REPLY PAGE-->

## What did you do?
-- After i had installed all dependencies using the "pnpm install" command.
--I created a folder inside the component folder and called it comment.
--I also created a page.tsx  in the guide folder as instructed.
--no dependencies were installed asides the existing one.
--i developed the comment and reply page and tested it.

Screenshot 2024-07-20 at 19 04 55
Screenshot 2024-07-20 at 19 05 31
Screenshot 2024-07-20 at 19 05 48
Screenshot 2024-07-20 at 19 05 51
Screenshot 2024-07-20 at 19 04 00
Screenshot 2024-07-20 at 19 04 50
Screenshot 2024-07-20 at 19 04 53

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [ x] The title and description of the PR is clear and explains the approach.
- [x ] I am making a pull request against the **dev branch** (left side).
- [x ] My commit messages styles matches our requested structure.
- [x ] My code additions will fail neither code linting checks nor unit test.
- [x ] I am only making changes to files I was requested to.

# Screenshots/Videos

### CODE REVIEW

**Comment by skeby** [comment]
Update your pr to show the required parts. If not, your pr wouldn't be reviewed

**Comment by onlyeugene** [comment]
i am confused
why required parts 🤦🏾‍♂️

**Comment by taiwonaf** [comment]
No code to review

**Comment by onlyeugene** [comment]
i have added the codes

**Comment by skeby** [comment]
> i have added the codes

lol
create a new pr with your changes

**Pull request closed without merging**
